### ISSUE TITLE
Testrun on MacOS 10.12.5 (Java build 1.8.0_102-b14) ends with exceptions

### ISSUE THREAD

**Issue by tloehr** [awegmann/consoleui#10]
I set up the consoleui environment. Built it with gradle. When I try to use the demonstration an exception occurs as soon as I try to select a list item with the cursor keys.

`Exception in thread "main" java.lang.UnsupportedOperationException: read() with timeout cannot be called as non-blocking operation is disabled`

![bildschirmfoto 2017-06-22 um 15 11 28](https://user-images.githubusercontent.com/961252/27435649-17dd5982-575d-11e7-8883-3df275ee98f4.png)

**Comment by awegmann** [comment]
Hi Thorsten.

I just tried this on my Mac. OS 10.12.5 / java 1.8.0_121. Works well. I'm working with iTerm instead of Apples Terminal, but I think it's a problem of the selected terminal type.

```
➜  ~ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
➜  ~ echo $TERM
xterm-256color
```
This is my environment. Maybe you can try another terminal setup?

**Comment by tloehr** [comment]
Sorry. Tried it also under Ubuntu Linux. Same effect. Changed the my TERM setting to `xterm-256color`, too.

![bildschirmfoto 2017-06-27 um 11 38 59](https://user-images.githubusercontent.com/961252/27581178-42167a2a-5b2d-11e7-899b-22699985f34b.png)

**Comment by awegmann** [comment]
Hi. I tried to reproduce your problem, but didn't succeed. The screenshot above shows, that your are using ssh to connect to srv0008 (which is the Linux box I guess?). Maybe you try this directly on the Linux machine? Because connecting with ssh is technically the same terminal than using this locally. 

Because the Exception comes from the underlying jline2 implementation, maybe we can get some help there.

**Comment by tloehr** [comment]
Ok. Had to fight myself through some cobweb in the server room. But I made it. Unfortunately with the same result.

![2017-07-03 11 47 08](https://user-images.githubusercontent.com/961252/27787612-a67bb61c-5fe5-11e7-8643-0f74a84f13bb.jpg)

**Comment by sivaprasadreddy** [comment]
I am getting the same error on Windows 8.1.

**Comment by awegmann** [comment]
I was never able to reproduce the problem. I hope the hotfix from @jribacruz fixed this.
