### ISSUE TITLE
ConsoleUI is not Responsive After Pressing Left or Right buttons on List Prompt

### ISSUE THREAD

**Issue by hashimati** [awegmann/consoleui#18]
![Screenshot from 2020-08-02 23-39-34](https://user-images.githubusercontent.com/1366461/89132034-e28cd300-d519-11ea-998b-99016ace8a44.png)

Hi, 

The application became not responsive after pressing left or right buttons on List Prompt menu. I've faced this issue on Linux. 

Regards, 
Ahmed.

**Comment by hashimati** [comment]
Hi, 

I'm facing the same issue if I'm pressing "Tab" or "Home" Buttons also.

**Comment by awegmann** [comment]
Hi Ahmed. I'll check that...

**Comment by awegmann** [comment]
Do you use a released version from maven central or did you compile it yourself?

**Comment by awegmann** [comment]
OK. I found out, that the bug is already fixed with code changes on the master branch. But I found another issue I have to fix before releasing a new version. Hopefully, I can release tomorrow.

**Comment by hashimati** [comment]
Hi Andreas, 

That's great!

**Comment by awegmann** [comment]
I just published version 0.0.11 to sonatype. This version should be available soon at maven central. Hope it fixes your issue.

**Comment by hashimati** [comment]
Hi Andreas, 

Thanks a lot. I'll check once it's available and I'll inform you after I trying it. 


Thanks again. 
Have a good night!

**Comment by awegmann** [comment]
Hi Ahmed. I just realized that I made a mistake at releasing the new version. It's currently not available at maven central. I can try tomorrow evening to release again. If you need the fix earlier I suggest downloading the master branch and build a local release on your own. 
Sorry.

**Comment by hashimati** [comment]
Hi Andreas, 

I've just build it and tried it. It works as expected. At the meantime, I'll use the local build and I'll be waiting for the new version on the Maven Central. I think you can close this issue. 

Thanks a lot Andreas. 
Ahmed

**Comment by awegmann** [comment]
Hi. Finally I releases `de.codeshelf.consoleui:consoleui:0.0.11` 

:-)

**Comment by awegmann** [comment]
Can you check if 0.0.11 is OK for you? Then I'll close the bug.

**Comment by hashimati** [comment]
Hi Andreas, 

I've just checked. It works as expected :)

Thanks a lot
