### ISSUE TITLE
lists higher than console causing scrolling issues and second list prompts doesn't align correctly

### ISSUE THREAD

**Issue by maxandersen** [awegmann/consoleui#20]
i'm trying to use consoleui in https://jbang.dev but having problems with lines overlapping and navigation being problematic. 

Better illustrated with this recording:

https://www.screencast.com/t/kZlRnXtbZEgq

Here is code showing the issue:

```
//usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 11+
//DEPS de.codeshelf.consoleui:consoleui:0.0.11


import de.codeshelf.consoleui.prompt.ConsolePrompt;
import de.codeshelf.consoleui.prompt.ListResult;
import de.codeshelf.consoleui.prompt.PromtResultItemIF;
import org.fusesource.jansi.AnsiConsole;

import java.io.IOException;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.fusesource.jansi.Ansi.ansi;

public class cuibug {

    public static void main(String... args) throws IOException {

        int max = 15;
        if(args.length>0) {
            max = Integer.valueOf(args[0]);
        }
        AnsiConsole.systemInstall();

        ConsolePrompt prompt = new ConsolePrompt();
        var builder = prompt.getPromptBuilder();

        var list = builder.createListPrompt()
                        .name("number")
                        .message("Numbers");

        var numbers = IntStream.rangeClosed(0,max).boxed().collect(Collectors.toList());
        numbers.forEach(i -> {
                    list.newItem(i.toString()).text(i.toString()).add();
        });


        list.addPrompt();

        Map<String, ? extends PromtResultItemIF> response = prompt.prompt(builder.build());

        String selid = ((ListResult)response.get("number")).getSelectedId();

        System.out.println(ansi().render("@|bold number:|@\n") + selid);


        builder = new ConsolePrompt().getPromptBuilder();
                builder.createListPrompt()
                        .name("choice")
                        .message("Action")
                        .newItem().name("copygradle").text("Copy Gradle to Clipboard").add()
                        .newItem("copymaven").text("Copy Maven to Clipboard").add()
                        .newItem("versions").text("Search older versions").add()
                        .newItem("quit").text("Quit").add()
                        .addPrompt();

                response = prompt.prompt(builder.build());

                System.out.println(response);

    }

}
```

Full example is at https://github.com/jbangdev/jbang-catalog/blob/master/gavsearch.java and you can run it using `jbang https://github.com/jbangdev/jbang-catalog/blob/master/gavsearch.java picocli`
or `jbang https://github.com/jbangdev/jbang-catalog/blob/master/gavsearch.java hibernate` to see it go really weird.

**Comment by awegmann** [comment]
Hi Max.

Yes, you're right. When the number of list or checkbox items is bigger than the screen size, it does not work correctly. I never implemented this. 
It's weird, my library is four years old and was never used much. But since about four weeks I'm getting more response and issues on that. OK - if consoleUI is used as an example of jbang I really need to fix this issue. ;-)

**Comment by awegmann** [comment]
And I also see, that the simple list prompt is not suitable for that large number of items. Even with scrolling. I guess I'll have to implement a list prompt with fuzzy search like [junegunn/fzf](https://github.com/junegunn/fzf) also.

**Comment by maxandersen** [comment]
:) if there was a way to know max items a list could fit I could at least work around that limitation for now; the "worse" thing is that the second list navigation just keeps going up - making it impossible to do more than just one interaction.

and yes, I hadn't spotted your library sooner - sorry about; its quite handy and unique in java to be able to handle these "basic" console uis this easily. I hope we can find a way to make it a bit more lenient - then it is quite perfect.

**Comment by awegmann** [comment]
I just pushed a new version which fixed the issue to the branch "bugfix/long_list_scrolling". I also added a more detailed documentation. I will test this new branch again, read the documentation again and then release a new version (maybe tomorrow).
