### ISSUE TITLE
redering list items does not clean the line correctly

### ISSUE THREAD

**Issue by awegmann** [awegmann/consoleui#22]
list items and choice items are not correctly rendered. 
Since version 0.0.12 scrolling is possible. When items with shorter text are rendered to a line with previous longer text, the old text stays there without erasing.

**Comment by awegmann** [comment]
fixed in version 0.0.13

**Comment by maxandersen** [comment]
awesome! works. now used in `jbang gavsearch@jbangdev` :)

is there a way to set the default height of the list ?
