### ISSUE TITLE
Running in IntelliJ Run Console

### ISSUE THREAD

**Issue by topbloc-beiswenger** [awegmann/consoleui#23]
I'd like to use this library to run codemods on an existing project by running code in a separate main method within the same project. When running my code through IntelliJ, however, the prompt gets sent to the console but there is no interactivity. Is it possible to run the application through IntelliJ and still get interactivity?

**Comment by awegmann** [comment]
Hi Matt. Maybe I misunderstand you, but I guess the "normal" output of a java application run from IntelliJ outputs to the tab "Console", which is not interactive. I guess this is intentionally not interactive. Does your app work from the build in terminal emulation?

**Comment by topbloc-beiswenger** [comment]
Hey Andreas, thanks for replying! I actually found out that what I'm looking for is not possible because of the lack of interactivity in IntelliJ's integrated terminal. There's already an [issue open for this](https://youtrack.jetbrains.com/issue/IDEA-86531) with JetBrains. 

Unfortunately, running this in IntelliJ's integrated terminal was a "must have" for the project so I was unable to go with this library and had to settle with a much more simple and "uglier" cli.

Nevertheless, I'm really happy that this library exists and hope to be able to use it in the future, thanks for providing this for the community!
