### ISSUE TITLE
Whitespace after completion

### ISSUE THREAD

**Issue by alecar-smi** [awegmann/consoleui#27]
I did notice that when adding completer, the console automatically insert a " " character at the end. This is particularly annoying with FileNameCompleter since I would want to complete (pressing TAB) many times before accepting the result 

example code:
`			.createInputPrompt()
			.name("folderWatcher").message("Cartella da monitorare")
			.addCompleter(new FileNameCompleter())
			.addPrompt()
			;
`

**Comment by awegmann** [comment]
Hi. Unfortuantely this is a question for Jline itself. The InputPromt in consoleUI is just a wrapper that uses ConsoleReader.readLine() for input. All the completer implementation is up to Jline.

**Comment by alecar-smi** [comment]
Hi, thanks for the reply.
The issue is imho in the InputPrompt, the private reader variable is initialized as new ConsoleReaderImpl();
I see no chance to cutomize the instance, since it is private and has no accesor.

The space is authomatically added from the completitionHandler inside the ConsoleReader. The handler itself (CandidateListCompletionHandler) has a boolean property named printSpaceAfterFullCompletion

I tried with the help of a debugger to set it to false (the default is true) and this solve the problem.

Unfortunately I'm not familiar enough with consoleui to understand where to eventually insert a configuration option to disable the automathic space

edit: see also https://github.com/jline/jline2/commit/a27f3bdd6df899224a3dc9d9f3a6511c6230c0b3
